// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://luaarxdiwvuztjfigtfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx1YWFyeGRpd3Z1enRqZmlndGZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyODI3MDEsImV4cCI6MjA2NTg1ODcwMX0._C1Tz7HEYEBNroMShZdO30S-Dk0tx_u-PzECCJSKP74";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);